'use strict';
const $=s=>document.querySelector(s),canvas=$('#apartment-canvas');
const roomNames=['Living room','Kitchen & dining','Bedroom','Games room','Artist’s corner','Bathroom','Entrance'];
let startupFailed=false;
const compatibilityRenderer=/AppleWebKit/i.test(navigator.userAgent)&&!/Chrome|Chromium|Edg\//i.test(navigator.userAgent)||new URLSearchParams(location.search).get('renderer')==='webgl';
let instance=null,starting=false,inside=false,current=0,density=1,lastResize=0,fpsSamples=[],visitTimer;
let prefs={lampSettings:{},theme:'day',quality:'auto',speed:1.5,sfx:true,atmosphere:true,reduced:matchMedia('(prefers-reduced-motion:reduce)').matches};try{prefs={...prefs,...JSON.parse(localStorage.getItem('apartment-preferences')||'{}')};}catch{}
function save(){try{localStorage.setItem('apartment-preferences',JSON.stringify(prefs));}catch{}}
function send(method,value=''){instance?.SendMessage('ApartmentExperience',method,String(value));}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,3500);}
function resize(){const rect=canvas.getBoundingClientRect();const maxPixels=prefs.quality==='light'?800000:prefs.quality==='detailed'?2400000:1500000;const d=Math.min(devicePixelRatio||1,prefs.quality==='light'?1:1.5,Math.sqrt(maxPixels/Math.max(1,rect.width*rect.height)))*density;canvas.width=Math.round(rect.width*d);canvas.height=Math.round(rect.height*d);lastResize=performance.now();}
function applyPrefs(){applyTheme();send('Comfort',prefs.reduced?'1':'0');send('Speed',prefs.speed);send('Quality',prefs.quality);document.body.classList.toggle('reduced',prefs.reduced);$('#quality').value=prefs.quality;$('#speed').value=prefs.speed;$('#reduced').checked=prefs.reduced;$('#sfx').checked=prefs.sfx;$('#atmosphere').checked=prefs.atmosphere;document.body.classList.toggle('atmosphere',prefs.atmosphere);density=1;resize();save();}
function panel(id,open){$(id).hidden=!open;if(id==='#settings'){if(open){stopJoy();pointer=null;}$('#menu-button').setAttribute('aria-expanded',String(open));send('Pause',open?'1':'0');}else $('#rooms-button').setAttribute('aria-expanded',String(open));}
function activate(){if($('#photo-preview').open)$('#photo-preview').close();panel('#settings',false);panel('#rooms',false);inside=true;document.body.classList.add('inside');$('#welcome').hidden=true;$('#tour').hidden=false;applyPrefs();send('Pause','0');canvas.focus();}
async function enter(){if(startupFailed){location.reload();return;}initAudio();if(instance){activate();return;}if(starting)return;starting=true;$('#enter').disabled=true;$('#loading').hidden=false;$('#load-status').textContent='Preparing your visit…';try{
 const res=await fetch('unity/build.json');if(!res.ok)throw Error('The tour is temporarily unavailable. Please try again.');const b=await res.json();
 if(!window.createUnityInstance)await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='unity/'+b.loader;script.onload=resolve;script.onerror=()=>{script.remove();reject(Error('Could not load the tour. Check your connection and try again.'));};document.body.append(script);});
 resize();instance=await createUnityInstance(canvas,{preRun:[module=>{if(compatibilityRenderer)module.SystemInfo.hasWebGPU=false;}],dataUrl:'unity/'+b.data,frameworkUrl:'unity/'+b.framework,codeUrl:'unity/'+b.wasm,streamingAssetsUrl:'unity/StreamingAssets',companyName:'Backbenchers',productName:'The Apartment',productVersion:'1.0.0',matchWebGLToCanvasSize:false,devicePixelRatio:1,showBanner:(message,type)=>{if(type==='error')console.error(message);}},progress=>{$('.progress i').style.width=Math.round(progress*100)+'%';$('#load-status').textContent=progress<.9?'Opening the apartment · '+Math.round(progress*100)+'%':'Arranging the last details…';});
 canvas.focus();
 await new Promise((resolve,reject)=>{const start=performance.now();const check=()=>{if(document.documentElement.dataset.renderer)return resolve();if(performance.now()-start>60000)return reject(Error('The apartment could not finish opening. Please reload and try again.'));setTimeout(check,100);};check();});
 window.apartment={visit,send,get instance(){return instance;},get state(){return{inside,current,density,quality:prefs.quality,theme:prefs.theme};}};activate();
 }catch(error){startupFailed=!!instance;$('#load-status').textContent=error.message||'The 3D tour could not start on this browser. Try an updated browser.';$('#enter').textContent=startupFailed?'Reload tour':'Try again';console.error(error);}finally{starting=false;$('#enter').disabled=false;}}
function visit(index){if(!instance)return;sound('visit');current=index;clearTimeout(visitTimer);document.body.classList.add('transitioning');send('Move','0,0');panel('#rooms',false);visitTimer=setTimeout(()=>{send('Visit',index);$('#room-name').textContent=roomNames[index];document.querySelectorAll('#rooms button').forEach((b,i)=>b.setAttribute('aria-current',String(i===index)));document.body.classList.remove('transitioning');canvas.focus();},prefs.reduced?0:210);}
$('#rooms').innerHTML=roomNames.map((name,i)=>`<button type="button" data-room="${i}" aria-current="${i===0}"><span>${name}</span><small>0${i+1}</small></button>`).join('');
$('#rooms').addEventListener('click',e=>{const b=e.target.closest('[data-room]');if(b)visit(Number(b.dataset.room));});$('#enter').onclick=enter;
$('#menu-button').onclick=()=>panel('#settings',$('#settings').hidden);$('#close-settings').onclick=()=>{panel('#settings',false);$('#menu-button').focus();};$('#rooms-button').onclick=()=>panel('#rooms',$('#rooms').hidden);
$('#quality').onchange=e=>{prefs.quality=e.target.value;applyPrefs();};$('#speed').oninput=e=>{prefs.speed=Number(e.target.value);send('Speed',prefs.speed);save();};$('#reduced').onchange=e=>{prefs.reduced=e.target.checked;applyPrefs();};
$('#reset').onclick=()=>{panel('#settings',false);visit(0);};$('#exit').onclick=()=>{panel('#settings',false);panel('#rooms',false);send('Pause','1');inside=false;document.body.classList.remove('inside');$('#welcome').hidden=false;$('#tour').hidden=true;$('#loading').hidden=true;$('#enter').focus();};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#experience').requestFullscreen();}catch{toast('Fullscreen is not available in this browser.');}};
$('#share').onclick=async()=>{const url=new URL('./',location.href).href;try{if(navigator.share)await navigator.share({title:'The Apartment — Backbenchers',url});else{await navigator.clipboard.writeText(url);toast('Apartment link copied');}}catch(e){if(e.name!=='AbortError')toast('Copy the address from your browser to share this apartment.');}};
let pointer=null,last={x:0,y:0},lookDown={x:0,y:0},lookDistance=0;canvas.addEventListener('pointerdown',e=>{if(!inside||!$('#settings').hidden)return;pointer=e.pointerId;last={x:e.clientX,y:e.clientY};lookDown={...last};lookDistance=0;canvas.setPointerCapture(pointer);canvas.focus();});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;lookDistance+=Math.hypot(e.clientX-last.x,e.clientY-last.y);send('Look',`${e.clientX-last.x},${e.clientY-last.y}`);last={x:e.clientX,y:e.clientY};});function releaseLook(e){if(e.pointerId!==pointer)return;if(e.type==='pointerup'&&lookDistance<8){const r=canvas.getBoundingClientRect();send('Pick',`${(e.clientX-r.left)/r.width},${(e.clientY-r.top)/r.height}`);}pointer=null;}canvas.addEventListener('pointerup',releaseLook);canvas.addEventListener('pointercancel',releaseLook);canvas.addEventListener('lostpointercapture',releaseLook);canvas.addEventListener('contextmenu',e=>e.preventDefault());
const joy=$('#joystick'),knob=joy.querySelector('span');let joyPointer=null;function moveJoy(e){const r=joy.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/38,y=(e.clientY-r.top-r.height/2)/38;const len=Math.hypot(x,y);if(len>1){x/=len;y/=len;}knob.style.transform=`translate(${x*36}px,${y*36}px)`;send('Move',`${x},${-y}`);}joy.addEventListener('pointerdown',e=>{if(joyPointer!==null)return;e.preventDefault();joyPointer=e.pointerId;joy.setPointerCapture(joyPointer);moveJoy(e);});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyPointer)moveJoy(e);});function stopJoy(e){if(e&&e.pointerId!==joyPointer)return;joyPointer=null;knob.style.transform='';send('Move','0,0');}joy.addEventListener('pointerup',stopJoy);joy.addEventListener('pointercancel',stopJoy);joy.addEventListener('lostpointercapture',stopJoy);
window.addEventListener('blur',()=>{pointer=null;stopJoy();send('Pause','1');});window.addEventListener('focus',()=>{if(inside&&$('#settings').hidden)send('Pause','0');});document.addEventListener('visibilitychange',()=>{stopJoy();send('Pause',document.hidden||!inside||!$('#settings').hidden?'1':'0');});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){panel('#settings',false);panel('#rooms',false);stopJoy();}if(inside&&document.activeElement===canvas&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();});
window.addEventListener('resize',resize);document.addEventListener('fullscreenchange',resize);window.addEventListener('apartment-frame',e=>{$('#performance').textContent=Math.round(e.detail.fps)+' fps · '+(document.documentElement.dataset.renderer||'3D')+' · '+prefs.quality+' detail';if(!inside||prefs.quality!=='auto'||document.hidden)return;fpsSamples.push(e.detail.fps);if(fpsSamples.length>4)fpsSamples.shift();if(fpsSamples.length===4&&performance.now()-lastResize>12000){const avg=fpsSamples.reduce((a,b)=>a+b)/4;const before=density;if(avg<52)density=Math.max(.6,density-.12);else if(avg>59)density=Math.min(1,density+.025);if(before!==density)resize();}});applyPrefs();

let audio=null;
function initAudio(){if(!prefs.sfx)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
function sound(kind){if(!prefs.sfx||!audio||audio.state!=='running')return;const now=audio.currentTime;const gain=audio.createGain();gain.connect(audio.destination);const duration=kind==='step'?.13:.075;gain.gain.setValueAtTime(kind==='step'?.035:.018,now);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);if(kind==='step'){const length=Math.floor(audio.sampleRate*.15),buffer=audio.createBuffer(1,length,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/length*6);const source=audio.createBufferSource(),filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=420;source.buffer=buffer;source.connect(filter);filter.connect(gain);source.start(now);source.stop(now+.16);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}else{const osc=audio.createOscillator();osc.type='sine';osc.frequency.setValueAtTime(kind==='visit'?420:640,now);osc.frequency.exponentialRampToValueAtTime(210,now+duration);osc.connect(gain);osc.start(now);osc.stop(now+duration);osc.onended=()=>{osc.disconnect();gain.disconnect();};}}
window.addEventListener('apartment-step',()=>{if(inside&&!document.hidden)sound('step');});
document.addEventListener('click',e=>{if(e.target.closest('button')){initAudio();sound('click');}});
$('#sfx').onchange=e=>{prefs.sfx=e.target.checked;save();if(prefs.sfx){initAudio();sound('click');}};
$('#atmosphere').onchange=e=>{prefs.atmosphere=e.target.checked;document.body.classList.toggle('atmosphere',prefs.atmosphere);save();};

let photoIndex=0;function photo(index){photoIndex=(index+roomNames.length)%roomNames.length;$('#photo-image').src='assets/'+(prefs.theme==='night'?'night-':'room-')+photoIndex+'.jpg';$('#photo-image').alt=roomNames[photoIndex]+' preview';$('#photo-title').textContent=roomNames[photoIndex];$('#photo-count').textContent=(photoIndex+1)+' / '+roomNames.length;}
$('#preview-open').onclick=()=>{photo(0);$('#photo-preview').showModal();};$('#photo-close').onclick=()=>$('#photo-preview').close();$('#photo-prev').onclick=()=>photo(photoIndex-1);$('#photo-next').onclick=()=>photo(photoIndex+1);$('#photo-enter').onclick=()=>{$('#photo-preview').close();enter();};$('#photo-preview').addEventListener('keydown',e=>{if(e.key==='ArrowRight'){photo(photoIndex+1);e.preventDefault();}if(e.key==='ArrowLeft'){photo(photoIndex-1);e.preventDefault();}});

function applyTheme(){
 const night=prefs.theme==='night';document.body.dataset.theme=night?'night':'day';send('Theme',night?'night':'day');
 $('#lighting').value=night?'night':'day';$('#theme-icon').textContent=night?'☾':'☀';$('.theme-label').textContent=night?' Midnight':' Daylight';$('#theme-toggle').setAttribute('aria-pressed',String(night));$('#theme-toggle').setAttribute('aria-label',night?'Switch to daylight lighting':'Switch to midnight lighting');
 $('.backdrop').src=night?'assets/apartment-night.jpg':'assets/apartment.jpg';
 $('#welcome>.eyebrow').textContent=night?'AN EVENING TO YOURSELF':'AN OPEN INVITATION';$('.intro').innerHTML=night?'Soft lights. A quieter world.<br>Stay a little longer. Make yourself at home.':'A little daylight. A slower pace.<br>A whole space to make yourself at home.';
 if($('#photo-preview').open)photo(photoIndex);applyFixtures();
}
function changeTheme(value){prefs.theme=value==='night'?'night':'day';document.body.classList.add('transitioning');setTimeout(()=>{applyTheme();save();document.body.classList.remove('transitioning');},prefs.reduced?0:210);sound('visit');}
$('#theme-toggle').onclick=()=>changeTheme(prefs.theme==='night'?'day':'night');$('#lighting').onchange=e=>changeTheme(e.target.value);

function lampState(){prefs.lampSettings??={};const key=prefs.theme==='night'?'night':'day';return prefs.lampSettings[key]??=( {power:true,master:1,warmth:key==='night'?25:75,lamps:[]} );}
function lampDefaults(){return{on:true,level:prefs.theme==='night'?.5:.25,color:prefs.theme==='night'?'#ffc78f':'#fff2d6'};}
function applyFixtures(){
 const labels=window.apartmentFixtureLabels||[],state=lampState(),list=$('#lamp-list');
 if(labels.length&&list.dataset.count!==String(labels.length)){list.innerHTML='';labels.forEach((label,i)=>{const row=document.createElement('details');row.className='lamp';row.dataset.lamp=i;row.innerHTML=`<summary><span class="lamp-name"></span><span class="lamp-dot"></span></summary><label class="check"><input type="checkbox" data-lamp-on="${i}">Lamp enabled</label><label>Brightness <output></output><input type="range" min="0" max="150" data-lamp-level="${i}"></label><label class="lamp-color">Light color<input type="color" data-lamp-color="${i}" aria-label="Light color"></label>`;row.querySelector('.lamp-name').textContent=label;list.append(row);});list.dataset.count=String(labels.length);}
 labels.forEach((_,i)=>{const lamp=state.lamps[i]??=(lampDefaults()),row=list.querySelector(`[data-lamp="${i}"]`);row.querySelector('[data-lamp-on]').checked=lamp.on;row.querySelector('[data-lamp-level]').value=Math.round(lamp.level*100);row.querySelector('output').textContent=Math.round(lamp.level*100)+'%';row.querySelector('[data-lamp-color]').value=lamp.color;row.querySelector('.lamp-dot').style.background=lamp.on&&state.power?lamp.color:'#555';send('Lamp',JSON.stringify({index:i,...lamp}));});
 $('#lights-power').checked=state.power;$('#lights-master').value=Math.round(state.master*100);$('#master-value').textContent=Math.round(state.master*100)+'%';$('#lights-warmth').value=state.warmth;send('Master',state.master);send('Power',state.power?'1':'0');
}
window.addEventListener('apartment-fixtures',()=>{if(instance)applyFixtures();});
window.addEventListener('apartment-fixture-selected',e=>{panel('#settings',true);$('#light-controls').open=true;const row=$(`[data-lamp="${e.detail}"]`);if(row){row.open=true;row.scrollIntoView({block:'nearest',behavior:prefs.reduced?'instant':'smooth'});row.querySelector('summary').focus();}});
$('#lamp-list').addEventListener('input',e=>{const row=e.target.closest('[data-lamp]');if(!row)return;const i=Number(row.dataset.lamp),lamp=lampState().lamps[i];if(e.target.matches('[data-lamp-on]'))lamp.on=e.target.checked;if(e.target.matches('[data-lamp-level]'))lamp.level=Number(e.target.value)/100;if(e.target.matches('[data-lamp-color]'))lamp.color=e.target.value;row.querySelector('output').textContent=Math.round(lamp.level*100)+'%';row.querySelector('.lamp-dot').style.background=lamp.on&&lampState().power?lamp.color:'#555';send('Lamp',JSON.stringify({index:i,...lamp}));save();});
$('#lights-master').oninput=e=>{lampState().master=Number(e.target.value)/100;$('#master-value').textContent=e.target.value+'%';send('Master',lampState().master);save();};$('#lights-power').onchange=e=>{lampState().power=e.target.checked;applyFixtures();save();};
$('#lights-warmth').oninput=e=>{const state=lampState();state.warmth=Number(e.target.value);const t=state.warmth/100,a=[255,180,108],b=[241,247,255];const color='#'+a.map((v,i)=>Math.round(v+(b[i]-v)*t).toString(16).padStart(2,'0')).join('');(window.apartmentFixtureLabels||[]).forEach((_,i)=>{state.lamps[i]??=lampDefaults();state.lamps[i].color=color;});applyFixtures();save();};
$('#lights-reset').onclick=()=>{delete prefs.lampSettings[prefs.theme==='night'?'night':'day'];applyFixtures();save();};
