const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/thomas/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const browser=await chromium.launch({headless:process.env.HEADLESS==='1',executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:process.env.WEBGL?['--disable-dawn-features=allow_unsafe_apis','--disable-webgpu']:[]});
 const errors=[],reports=[];try{
 const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1});if(process.env.WEBGL)await context.addInitScript(()=>Object.defineProperty(navigator,'gpu',{value:undefined}));const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await p.addInitScript(()=>{window.__steps=0;window.addEventListener('apartment-step',()=>window.__steps++);window.__frames=[];window.addEventListener('apartment-frame',e=>window.__frames.push(e.detail));});
 await p.goto(process.env.APARTMENT_URL||'http://localhost:8770');await p.bringToFront();await p.screenshot({path:'/tmp/apartment-welcome.png'});
 assert.equal(await p.locator('meta[property="og:image"]').count(),1);assert((await p.locator('meta[property="og:image"]').getAttribute('content')).startsWith('https://'));
 await p.locator('#preview-open').click();for(let i=0;i<7;i++){await p.locator('#photo-image').evaluate(img=>img.decode());await p.locator('#photo-next').click();}await p.locator('#photo-close').click();await p.locator('#enter').click();await p.locator('#tour').waitFor({state:'visible',timeout:180000});await p.waitForTimeout(4000);
 for(let i=0;i<7;i++){await p.locator('#rooms-button').click();await p.locator(`[data-room="${i}"]`).click();await p.waitForTimeout(1300);await p.screenshot({path:`/tmp/apartment-room-${i}.png`});assert.equal(await p.locator(`[data-room="${i}"]`).getAttribute('aria-current'),'true');}
 await p.evaluate(()=>apartment.visit(0));await p.waitForTimeout(2400);const before=await p.evaluate(()=>__frames.at(-1));await p.locator('#apartment-canvas').focus();await p.keyboard.down('d');await p.waitForTimeout(1500);await p.keyboard.up('d');await p.waitForTimeout(2200);const after=await p.evaluate(()=>__frames.at(-1));assert(Math.hypot(after.x-before.x,after.z-before.z)>.2,'walking must change world position');assert(await p.evaluate(()=>__steps)>0,'footsteps must follow real movement');assert.equal(await p.evaluate(()=>audio.state),'running');reports.push({movement:{before,after},renderer:await p.evaluate(()=>document.documentElement.dataset.renderer)});
 await p.screenshot({path:'/tmp/apartment-day-before.png'});await p.locator('#theme-toggle').click();await p.waitForTimeout(900);assert.equal(await p.evaluate(()=>apartment.state.theme),'night');assert.equal(await p.locator('body').getAttribute('data-theme'),'night');await p.screenshot({path:'/tmp/apartment-midnight.png'});for(let i=0;i<7;i++){await p.evaluate(i=>apartment.visit(i),i);await p.waitForTimeout(900);await p.screenshot({path:`/tmp/apartment-night-room-${i}.png`});}await p.locator('#theme-toggle').click();await p.waitForTimeout(900);assert.equal(await p.evaluate(()=>apartment.state.theme),'day');await p.screenshot({path:'/tmp/apartment-daylight.png'});await p.locator('#menu-button').click();await p.locator('#quality').selectOption('light');await p.locator('#reduced').check();await p.locator('#close-settings').click();assert.equal(await p.evaluate(()=>apartment.state.quality),'light');assert(await p.locator('body').evaluate(e=>e.classList.contains('reduced')));
 for(const [width,height]of [[320,568],[390,844],[844,390],[1440,900]]){await p.setViewportSize({width,height});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);const dock=await p.locator('.bottom-bar').boundingBox();assert(dock.y+dock.height<=height+1,'controls must remain visible in landscape');await p.locator('#menu-button').click();const b=await p.locator('#settings').boundingBox();assert(b.x>=0&&b.x+b.width<=width+1&&b.y+b.height<=height+1);await p.screenshot({path:`/tmp/apartment-menu-${width}.png`});await p.locator('#close-settings').click();}
 await p.locator('#menu-button').click();await p.locator('#exit').click();assert(await p.locator('#welcome').isVisible());await p.locator('#enter').click();await p.waitForTimeout(1000);assert(await p.locator('#tour').isVisible());reports.push({frames:await p.evaluate(()=>__frames.slice(-8))});
 await context.close();const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));if(process.env.WEBGL)await mobile.addInitScript(()=>Object.defineProperty(navigator,'gpu',{value:undefined}));await m.addInitScript(()=>{window.__sent=[];window.__mobileFrames=[];window.addEventListener('apartment-frame',e=>__mobileFrames.push(e.detail));});await m.route('**/apartment.js*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace("function send(method,value=''){","function send(method,value=''){window.__sent.push([method,value]);")});});await m.goto(process.env.APARTMENT_URL||'http://localhost:8770');await m.bringToFront();await m.locator('#enter').click();await m.locator('#tour').waitFor({state:'visible',timeout:180000});await m.waitForFunction(()=>__mobileFrames.length>1);reports.push({mobileRenderer:await m.evaluate(()=>document.documentElement.dataset.renderer),mobileFrames:await m.evaluate(()=>__mobileFrames)});
 await m.locator('#theme-toggle').click();await m.waitForTimeout(600);assert.equal(await m.evaluate(()=>apartment.state.theme),'night');await m.screenshot({path:'/tmp/apartment-mobile-night.png'});await m.locator('#theme-toggle').click();await m.waitForTimeout(600);const cdp=await mobile.newCDPSession(m),touch=(type,touchPoints)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints});const a={x:86,y:653,id:1},b={x:295,y:330,id:2};await touch('touchStart',[a]);await touch('touchMove',[{...a,y:621}]);await touch('touchStart',[{...a,y:621},b]);await touch('touchMove',[{...a,y:621},{...b,x:260}]);await touch('touchEnd',[{...a,y:621}]);await touch('touchEnd',[]);const sent=await m.evaluate(()=>__sent);assert(sent.some(([k,v])=>k==='Move'&&Number(v.split(',')[1])>.5));assert(sent.some(([k])=>k==='Look'));assert.equal(sent.filter(([k])=>k==='Move').at(-1)[1],'0,0');await m.screenshot({path:'/tmp/apartment-mobile.png'});
 if(process.env.WEBGL)assert.equal(reports[0].renderer,'OpenGLES3');assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,errors,reports},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
